FROM postgres:14.23-alpine3.23

ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
ARG DB_NAME

ENV POSTGRES_USER=$DATABASE_USERNAME
ENV POSTGRES_PASSWORD=$DATABASE_PASSWORD
ENV DB_NAME=$DB_NAME

EXPOSE 5432

VOLUME db_postgres:/var/lib/postgresql/data