name: db-ci
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Login no DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker imagem build do banco de dados
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./postgres.dockerfile
          push: true
          tags: lucasbr27/db-postgres:latest
          build-args: |
            DB_NAME=${{ secrets.DB_NAME }}
            DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}